# Base configs
baseurl: ""
image_fulls_loc: "/images/fulls"
image_thumbs_loc: "/images/thumbs"
#google_analytics: "UA-109060453-1"
# UI configs
title: "Fotografia por Nuno Gandra"
subtitle: "Como eu vejo o mundo!"
author: "Nuno Gandra"
header:
 title: "Fotografia"
 subtitle: "Nuno Gandra"
footer:
 name: "Nuno Gandra"
 bio: "Como se vê, não sou fotógrafo!"
web_design: "nunogand"
social_urls:
# facebook: "https://www.facebook.com"
 twitter: "https://www.twitter.com/nunogand"
# instagram: "https://www.instagram.com/nunogand"
# dribbble: "https://dribbble.com/"
 linkedin: "https://www.linkedin.com/in/nunogand/"
 github: "https://www.github.com/nunogand"

 plugins:
  - jekyll-seo-tag
  - jekyll-sitemap